name: device-sdk-go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: go-vet-and-test
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
      id: go
    - name: Cache go modules  
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key:  v3-go-modules
        restore-keys: v3-go-modules
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: vet and test v3
      run: |
        cd v3 ; go vet ./... ; cd -
        cd v3 ; go test ./... ; cd -
